### ISSUE TITLE
Fail - Add altitude information to some track points 

### ISSUE THREAD

**Issue by davilocho** [opoto/wtracks#1]
First of all thank you for your work, it is truly incredible. That's why I made a contribution towards your paypal.

As a contribution I wanted to tell you that there is a failure in the functionality of "Elevate (Add altitude information to some track points" since when it crosses the results in the line 1202 of the file "wtracks.js" generates an error for not being defined the prop elevation in those results.I pass some captures in case you are of help.

I thank you again for your work, it's very good.
![captura](https://user-images.githubusercontent.com/7192768/31319355-083f7640-ac62-11e7-8315-c42115d4bc88.png)

**Comment by opoto** [comment]
Thank you for your report. 

The error on the right of your screenshot is not about an undefined elevation, but about an undefined results[i]. There was actually a set of small mistakes in the code, which only appears when using very long tracks, which is why nobody reported it so far.
I hope this is fixed by ee380d5. Please confirm so that I can close this issue.

Note that too many elevation requests might eventually exhaust WTracks's elevation service daily quota, leading to "Elevation failed" error message on the top right of the page. The quota is reset every day.

One interesting point about your screenshot is that it shows the elevation service replied "OK", meaning there should be a valid elevation response, but all elevation values are "undefined". I've never seen this behavior, maybe elevation service does not know the elevation of the coordinates you are asking for. Can you share the track or at least a few coordinates with which you have this error so that I can check?
